### ISSUE TITLE
Add proper licencing information, README.md, repo tags and repo description

### ISSUE THREAD

**Issue by farooqkz** [W4IT-Dev/Falling-Numbers#1]
- Licencing means under what conditions people can use your game. Can they sell it? Can they give it to the others as a gift? Can they change it and re-publish it under the same name as you do? Can they change it and name it their own? And a lot more.
 - README of a repository tells other Github users what this repository is about
 - Repo tags will help people on Github find out about different repositories. You can add "kaios", "kaios-game", "webapp", "game", "2d-game" and so on.
 - Repo description gives a summary what this repo is about in the search results
 - For licencing, the code cannot be under a CreativeCommons licence(except CC0). The CC family are for media, font and such these.

**Comment by W4IT-Dev** [comment]
License file done
README done
tags, how do i do that?
descrpition, didnt check yet but i dont think i know where that is

**Comment by farooqkz** [comment]
In the repo homepage, on the right side
