### ISSUE TITLE
Resize the PNG media files

### ISSUE THREAD

**Issue by farooqkz** [W4IT-Dev/Falling-Numbers#3]
The digit files are too big and thus wasting space. KaiOS phones screen is not that big so I would suggest downsizing the digit PNGs as well as the background image.

**Comment by W4IT-Dev** [comment]
I have succesfully compressed all images and now they only take up 90KB and I might compress them even more.

**Comment by farooqkz** [comment]
> I have succesfully compressed all images and now they only take up 90KB and I might compress them even more.

That's good but if you want, the digits can take even less space if you downsize them. For instance, `0.png` is currently 2KB and its resolution is 160x253. You can resize it to 15x24 and it'll take less than a KB(for me it's 628 bytes). But you can even do more optimization. Since the digit sprites are just black and white, there is no need to use 4bit color map.

**Comment by W4IT-Dev** [comment]
I now compressed the digits and other images even more, I hope its enough.
The whole app is a bit over 400KB now.

**Comment by farooqkz** [comment]
Well you can optimize even more especially since the effort is trivial. I'd say 400KB is not little for KaiOS

**Comment by W4IT-Dev** [comment]
I compressed the audio under 200KB but it sounded weird then.

**Comment by farooqkz** [comment]
> I compressed the audio under 200KB but it sounded weird then.

You don't need to compress it just make it mono. I think that's enough.

**Comment by W4IT-Dev** [comment]
I already did that, didn't I?

**Comment by farooqkz** [comment]
> I already did that, didn't I?

Yeah but aren't you also trying to further compress it?

**Comment by W4IT-Dev** [comment]
I did try yes, but as I said it gets weird

**Comment by farooqkz** [comment]
> I did try yes, but as I said it gets weird

It's okay. You already reduced about 300KB and that's a lot especially for KaiOS.

**Comment by W4IT-Dev** [comment]
Yea
Origianal version to this version now is -1MB
Before it was 1.45 MB and now its under 450KB

**Comment by farooqkz** [comment]
I'd say even 450KB is too much for such a simple game of yours. There are tons of game like this one. If your game is not that complex, it shouldn't take a LOT of space.
